INSERT INTO public.unit(id, name) VALUES 
(uuid_generate_v4(), 'No aplica'),
(uuid_generate_v4(), 'Unidad'),
(uuid_generate_v4(), 'Pieza'),
(uuid_generate_v4(), 'Millar'),
(uuid_generate_v4(), 'Metro'),
(uuid_generate_v4(), 'Par'),
(uuid_generate_v4(), 'Número de pares'),
(uuid_generate_v4(), 'Caja'),
(uuid_generate_v4(), 'Tambor'),
(uuid_generate_v4(), 'Centímetro'),
(uuid_generate_v4(), 'Pulgada'),
(uuid_generate_v4(), 'Pie'),
(uuid_generate_v4(), 'Centímetro cuadrado'),
(uuid_generate_v4(), 'Metro cuadrado'),
(uuid_generate_v4(), 'Pulgada cuadrada'),
(uuid_generate_v4(), 'Mililitro'),
(uuid_generate_v4(), 'Litro'),
(uuid_generate_v4(), 'Galón'),
(uuid_generate_v4(), 'Gramo'),
(uuid_generate_v4(), 'Kilogramo'),
(uuid_generate_v4(), 'Tonelada'),
(uuid_generate_v4(), 'Libra'),
(uuid_generate_v4(), 'Metro cúbico'),
(uuid_generate_v4(), 'Hora'),
(uuid_generate_v4(), 'Minuto'),
(uuid_generate_v4(), 'Día'),
(uuid_generate_v4(), 'Hectárea'),
(uuid_generate_v4(), 'Ampolla'),
(uuid_generate_v4(), 'Frasco'),
(uuid_generate_v4(), 'Paquete'),
(uuid_generate_v4(), 'Sobre'),
(uuid_generate_v4(), 'Tarro'),
(uuid_generate_v4(), 'Tubo'),
(uuid_generate_v4(), 'Decímetro'),
(uuid_generate_v4(), 'Metro lineal'),
(uuid_generate_v4(), 'Kilómetro'),
(uuid_generate_v4(), 'Radianes');