name: ci

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  release:
    types: [released]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-latest

    steps:
      - name: cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  lint:
    runs-on: ubuntu-latest
    name: lint project
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - run: pnpm lint

  test:
    runs-on: ubuntu-latest
    name: test project
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - run: pnpm test

  format:
    runs-on: ubuntu-latest
    name: format code
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - run: pnpm format

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: format code"
